### ISSUE TITLE
docker/build COPY error on step 12/13

### ISSUE THREAD

**Issue by mattdeak** [ntaylorwss/megatron#2]
docker/build errors out on step 12/13.
> Step 12/13 : COPY pipeline/ /usr/local/lib/python3.6/dist-packages/pipeline
COPY failed: stat /var/lib/docker/tmp/docker-builder128517697/pipeline: no such file or directory

Docker Version: `18.06.0-ce`, build `0ffa825`

**Comment by squarebridges** [comment]
All references to pipeline should have been renamed to megatron. Does this still happen with the latest commit?

**Comment by jeremyjordan** [comment]
I'm getting:

`docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/megatron/manifests/latest: unauthorized: incorrect username or password.`

**Comment by jeremyjordan** [comment]
ran `docker/build` on the latest commit, no problems

**Comment by squarebridges** [comment]
Seems like it's been fixed.
